packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  "@types/node": ^20.11.24
  "@types/eslint": ^8.56.5
  tailwind-merge: "^2.5.4"
  tailwindcss-animate: "^1.0.7"
  postcss: ^8.4.47
  vitest: ^2.1.3
  "@biomejs/biome": ^1.9.4

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0
